"""add last_added timestamp for history

Revision ID: 2408b9314fbc
Revises: f88271e16ddb
Create Date: 2020-09-21 20:18:24.676715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2408b9314fbc'
down_revision = 'f88271e16ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('last_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'last_added')
    # ### end Alembic commands ###
